apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "rkamradt-platform",
          "Group": "Servers",
          "Host": "{{ .Values.postgresql.host }}",
          "Port": {{ .Values.postgresql.port }},
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer"
        }
      }
    }
