apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgadmin
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pgadmin
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
