apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-routes
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  routes.yaml: |
    {{ .Values.routes | nindent 4 }}
