apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: 9092
    protocol: TCP
    name: kafka
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: kafka-internal
  selector:
    app: kafka
