apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: {{ .Values.service.grpcPort }}
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: {{ .Values.service.grpcPort }}
    protocol: TCP
    name: grpc
  - port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}
