apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
  type: {{ .Values.service.api.type }}
  selector:
    app: minio
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 9000
      protocol: TCP
      name: api
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
  type: {{ .Values.service.console.type }}
  selector:
    app: minio
  ports:
    - port: {{ .Values.service.console.port }}
      targetPort: 9001
      protocol: TCP
      name: console
