repoURL: https://github.com/rkamradt/rkamradt-helm-charts
targetRevision: main

apps:
  - name: kafka
    path: kafka
    namespace: kafka
  - name: mongodb
    path: mongodb
    namespace: mongodb
  - name: postgresql
    path: postgresql
    namespace: postgresql
  - name: manufacturing-service
    path: manufacturing-service
    namespace: rkamradt-platform
