repoURL: https://github.com/rkamradt/rkamradt-helm-charts
targetRevision: main

apps:
  - name: axon-server
    path: axon-server
    namespace: axon-server
  - name: kafka
    path: kafka
    namespace: kafka
  - name: mongodb
    path: mongodb
    namespace: mongodb
  - name: postgresql
    path: postgresql
    namespace: postgresql
  - name: manufacturing-service
    path: manufacturing-service
    namespace: rkamradt-platform
  - name: vehicleupdateservice
    path: vehicleupdateservice
    namespace: rkamradt-platform
  - name: vehiclequeryservice
    path: vehiclequeryservice
    namespace: rkamradt-platform
  - name: lotupdateservice
    path: lotupdateservice
    namespace: rkamradt-platform
  - name: lotqueryservice
    path: lotqueryservice
    namespace: rkamradt-platform
  - name: clodapp
    path: clodapp
    namespace: clodapp
    versionValuesFile: version-values.yaml
  - name: api-gateway
    path: api-gateway
    namespace: api-gateway
    versionValuesFile: version-values.yaml
  - name: architectai
    path: architectai
    namespace: rkamradt-platform
  - name: architectai-api
    path: architectai-api
    namespace: rkamradt-platform
